# Generated by Django 2.1.5 on 2019-01-10 15:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyBox',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('check_sum', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('activation_status', models.BooleanField(default=False, null=True)),
                ('issue_status', models.BooleanField(default=False, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('counter_write_off', models.BooleanField(blank=True, default=False, editable=False, null=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='KeyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys_amount', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
            ],
        ),
        migrations.AddField(
            model_name='keybox',
            name='key_counter',
            field=models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chekpoint.KeyCounter'),
        ),
        migrations.AddField(
            model_name='keybox',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
