# Generated by Django 2.1.5 on 2019-01-09 00:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyBox',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key_code', models.CharField(blank=True, max_length=4)),
                ('check_sum', models.CharField(blank=True, max_length=32)),
                ('activation_status', models.BooleanField(default=None)),
                ('issue_status', models.BooleanField(default=False)),
                ('keys_amount', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
