# Generated by Django 2.1.5 on 2019-01-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keybox',
            name='activation_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
