# Generated by Django 2.1.5 on 2019-01-10 16:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chekpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keybox',
            name='activation_status',
            field=models.BooleanField(default=False, null=True, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='check_sum',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Контрольная сумма'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время активации'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='issue_status',
            field=models.BooleanField(default=False, null=True, verbose_name='Выдан'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='key_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='key_counter',
            field=models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chekpoint.KeyCounter', verbose_name='Осталось'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='keybox',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='keycounter',
            name='keys_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Счётчик остатка'),
        ),
    ]
