# Generated by Django 2.1.5 on 2019-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chekpoint', '0002_auto_20190110_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='keybox',
            name='counter_write_off',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
